### ISSUE TITLE
Examples link on pypi not working

### ISSUE THREAD

**Issue by gdbarron** [Venafi/vcert-python#103]
**PROBLEM SUMMARY**
The link to examples, https://pypi.org/examples, on https://pypi.org/project/vcert/ does not work.  The same link from github's readme is fine.

**STEPS TO REPRODUCE**
Click the link :)

**EXPECTED RESULTS**

**ACTUAL RESULTS**

**ENVIRONMENT DETAILS**

**COMMENTS/WORKAROUNDS**

**Comment by rvelaVenafi** [comment]
Hello there @gdbarron , thanks for highlighting this issue, it is happening because the README.MD is using a relative path to the examples folder which works on github but not on the pypi release. Will fix it on next release.
