### ISSUE TITLE
pip vcert dependencies

### ISSUE THREAD

**Issue by laroggo** [Venafi/vcert-python#134]
Is there any reason the dependencies can't be `>=` vs `==` ?

**Comment by rvelaVenafi** [comment]
I know this is a late response. The reason is to control vulnerabilities and ensure a middle man cannot provide a malicious new version of a known library and you automatically upgrade to it.

**Comment by MallocArray** [comment]
This is particularly problematic when these pinned requirements aren't being updated by the vcert-python repository maintainers, so now we are on very old versions
https://github.com/Venafi/vcert-python/issues/177

This is resulting in being forced into a more vulnerable position than if the requirements were set to minimums and let packages update as the individual projects update their code.
